<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="14" passed="11" failed="1" skipped="2">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-06-11T06:24:38Z" name="Sanket TestNG suite" finished-at="2022-06-11T06:24:39Z" duration-ms="146">
    <groups>
    </groups>
    <test started-at="2022-06-11T06:24:38Z" name=" my testng pactise test" finished-at="2022-06-11T06:24:39Z" duration-ms="146">
      <class name="TestNGSessions.InvocationCountConcept">
        <test-method signature="createuser()[pri:0, instance:TestNGSessions.InvocationCountConcept@2de23121]" started-at="2022-06-11T06:24:38Z" name="createuser" finished-at="2022-06-11T06:24:38Z" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createuser -->
        <test-method signature="createuser()[pri:0, instance:TestNGSessions.InvocationCountConcept@2de23121]" started-at="2022-06-11T06:24:38Z" name="createuser" finished-at="2022-06-11T06:24:38Z" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createuser -->
        <test-method signature="createuser()[pri:0, instance:TestNGSessions.InvocationCountConcept@2de23121]" started-at="2022-06-11T06:24:38Z" name="createuser" finished-at="2022-06-11T06:24:38Z" duration-ms="8" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createuser -->
        <test-method signature="createuser()[pri:0, instance:TestNGSessions.InvocationCountConcept@2de23121]" started-at="2022-06-11T06:24:38Z" name="createuser" finished-at="2022-06-11T06:24:38Z" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createuser -->
        <test-method signature="createuser()[pri:0, instance:TestNGSessions.InvocationCountConcept@2de23121]" started-at="2022-06-11T06:24:38Z" name="createuser" finished-at="2022-06-11T06:24:38Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createuser -->
        <test-method signature="createuser()[pri:0, instance:TestNGSessions.InvocationCountConcept@2de23121]" started-at="2022-06-11T06:24:38Z" name="createuser" finished-at="2022-06-11T06:24:38Z" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createuser -->
        <test-method signature="createuser()[pri:0, instance:TestNGSessions.InvocationCountConcept@2de23121]" started-at="2022-06-11T06:24:38Z" name="createuser" finished-at="2022-06-11T06:24:38Z" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createuser -->
        <test-method signature="createuser()[pri:0, instance:TestNGSessions.InvocationCountConcept@2de23121]" started-at="2022-06-11T06:24:38Z" name="createuser" finished-at="2022-06-11T06:24:38Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createuser -->
        <test-method signature="createuser()[pri:0, instance:TestNGSessions.InvocationCountConcept@2de23121]" started-at="2022-06-11T06:24:39Z" name="createuser" finished-at="2022-06-11T06:24:39Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createuser -->
        <test-method signature="createuser()[pri:0, instance:TestNGSessions.InvocationCountConcept@2de23121]" started-at="2022-06-11T06:24:39Z" name="createuser" finished-at="2022-06-11T06:24:39Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createuser -->
      </class> <!-- TestNGSessions.InvocationCountConcept -->
      <class name="TestNGSessions.DependOnMethod">
        <test-method signature="loginTest()[pri:1, instance:TestNGSessions.DependOnMethod@587e5365]" started-at="2022-06-11T06:24:39Z" name="loginTest" finished-at="2022-06-11T06:24:39Z" duration-ms="2" status="FAIL">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
at TestNGSessions.DependOnMethod.loginTest(DependOnMethod.java:10)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method signature="homepageTestTest()[pri:2, instance:TestNGSessions.DependOnMethod@587e5365]" started-at="2022-06-11T06:24:39Z" name="homepageTestTest" finished-at="2022-06-11T06:24:39Z" depends-on-methods="TestNGSessions.DependOnMethod.loginTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method DependOnMethod.homepageTestTest()[pri:2, instance:TestNGSessions.DependOnMethod@587e5365] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method DependOnMethod.homepageTestTest()[pri:2, instance:TestNGSessions.DependOnMethod@587e5365] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- homepageTestTest -->
        <test-method signature="SearchTest()[pri:3, instance:TestNGSessions.DependOnMethod@587e5365]" started-at="2022-06-11T06:24:39Z" name="SearchTest" finished-at="2022-06-11T06:24:39Z" depends-on-methods="TestNGSessions.DependOnMethod.loginTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method DependOnMethod.SearchTest()[pri:3, instance:TestNGSessions.DependOnMethod@587e5365] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method DependOnMethod.SearchTest()[pri:3, instance:TestNGSessions.DependOnMethod@587e5365] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SearchTest -->
      </class> <!-- TestNGSessions.DependOnMethod -->
      <class name="TestNGSessions.ExpectedExceptionConcept">
        <test-method signature="loginTest()[pri:0, instance:TestNGSessions.ExpectedExceptionConcept@22fcf7ab]" started-at="2022-06-11T06:24:38Z" name="loginTest" finished-at="2022-06-11T06:24:38Z" duration-ms="16" status="PASS">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
at TestNGSessions.ExpectedExceptionConcept.loginTest(ExpectedExceptionConcept.java:12)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
      </class> <!-- TestNGSessions.ExpectedExceptionConcept -->
    </test> <!--  my testng pactise test -->
  </suite> <!-- Sanket TestNG suite -->
</testng-results>
